---
output: pdf_document
---
  
## Multi-scale assessment of a grassland productivity model
**Shawn D. Taylor, Dawn M. Browning**
  
Supplementary Model Equations and Parameters

The PhenoGrass model from Hufkens et al. 2016 takes the following form:

\begin{equation}
W_{t+1} = W_{t} + P_{t} - (1-V_{t})/(D_{t}/(W_{cap}-{W_p}))^{2}E_{t}-gb_{3}D_{t}V_{t}
\end{equation}

\begin{equation}
V_{t+1} = V_{t} + gS_{t}b_{1}D_{t-L}(1-V_{t}/V_{max})-db_{2}(1-V_{t})V_{t}
\end{equation}

\begin{equation}
D_{t} = max(0,W_{t}-W_{p})
\end{equation}

\begin{equation}
W_{t} = max(0,min(W_{cap},W_{t}))
\end{equation}

\begin{equation}
V_{t} = max(0,min(V_{max},V_{t}))
\end{equation}

\begin{equation}
\left\{\begin{matrix}
D_{t-L} > D_{t-L-1}; & d=0\\ 
D_{t-L} \leq  D_{t-L-1}; & d=1 
\end{matrix}\right.
\end{equation}

\begin{equation}
S_{t} = (TOA_{t} - Phmin)/(Phmax - Phmin)
\end{equation}

\begin{equation}
\left\{\begin{matrix}
S_{t-1} > S_{t}; & d=1  \\
S_{t-1} \leq  S_{t}; & d=0 
\end{matrix}\right.
\end{equation}

\begin{equation}
g = (\frac{T_{max}-T_{m}}{T_{max}-T_{opt}})(\frac{T_{m}}{T_{opt}})^{(\frac{T_{opt}}{T_{max}-T_{opt}})}
\end{equation}

The vegetaion parameter V corresponds to the fCover, which is mapped to PhenoCam G\textsubscript{cc} using the transfer function based on the relationship between annual precipitation and fractional vegetation cover (Donohue et al. 2013).:

\begin{equation}
S_{c} = MAP/(MAP+h)
\end{equation}

where:
\begin{equation}
fCover = G_{cc}*S_{c}
\end{equation}

MAP is the site level mean annual precipitation, and \textit{h} is an estimated parameter. G\textsubscript{cc} is a ratio of the green band within the daily image ROI:

\begin{equation}
G_{cc} = \frac{G_{dn}}{G_{dn}+R_{dn}+B_{dn}}
\end{equation}

Where G\textsubscript{dn}, R\textsubscript{dn}, and B\textsubscript{dn} are the mean digitial numbers for green, red, and blue channels, respectively. See Richardson et al. 2018 for further G\textsubscript{cc} processing details. 

\newpage

\begin{table}[]
\begin{tabular}{lll}
                              & Parameter               & Description                                  \\
\textbf{State Variables}      & W                       & Soil Water Content (mm)                      \\
                             & V                       & Fractional Cover (fCover)                    \\
                             & D                       & Plant available water (mm)                   \\
                             & g                       & Plant temperature response function          \\
\textbf{Input Variables}      & P                       & Precipitaiton (mm)                           \\
                             & MAP                     & Mean annual precipitation (mm)                \\
                             & W\textsubscript{cap}    & Soil Field Capacity (mm)                     \\
                             & W\textsubscript{p}      & Soil Wilting Point (mm)                      \\
                             & V\textsubscript{max}    & Maximum vegetation cover (1.0)               \\
                             & E                       & Evapotranspiration (mm)                      \\
                             & T\textsubscript{m}      & Running 15 day mean temperature (C)          \\
                             & TOA                     & Top of atmosphere radiation                  \\
                             & T\textsubscript{max}    & Maximum temperature for growth (45 C)        \\
                             & T\textsubscript{min}    & Minimum temperature for growth (0 C)         \\
\textbf{Estimated Parameters} & b1                      & Vegetation growth parameter                  \\
                             & b2                      & Senescence parameter                         \\
                             & b3                      & Soil water extraction rate                   \\
                             & T\textsubscript{opt}    & Optimal vegetation growth temperature        \\
                             & Phmin                   & Lower bound of optimal daily solar radiation \\
                             & Phmax                   & Upper bound of optimal daily solar radiation \\
                             & L                       & Lag (days)                                    \\
                             & h                       & fCover Transfer function parameter                                           
\end{tabular}
\end{table}

## References
Donohue, R. J., Roderick, M. L., McVicar, T. R., & Farquhar, G. D. (2013). Impact of CO 2 fertilization on maximum foliage cover across the globe’s warm, arid environments. Geophysical Research Letters, 40(12), 3031–3035. https://doi.org/10.1002/grl.50563  
Hufkens, K., Keenan, T. F., Flanagan, L. B., Scott, R. L., Bernacchi, C. J., Joo, E., … Richardson, A. D. (2016). Productivity of North American grasslands is increased under future climate scenarios despite rising aridity. Nature Climate Change, 6(7), 710–714. https://doi.org/10.1038/nclimate2942  
Richardson, A. D., Hufkens, K., Milliman, T., Aubrecht, D. M., Chen, M., Gray, J. M., … Frolking, S. (2018). Tracking vegetation phenology across diverse North American biomes using PhenoCam imagery. Scientific Data, 5(1), 180028. https://doi.org/10.1038/sdata.2018.28  
